# Site settings ...
uri: service-dev-junior.github.io 
url: https://service-dev-junior.github.io
name: ServiceDevJunior
title: 서비스개발본부 주니어
email: supreme2705@daou.co.kr
author: servicedev
baseurl: ""
keywords: "Your, Keyword, Here"
description: "서비스 개발 본부 주니어들의 블로그입니다."
social_username: username

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
